"""Cloud Function (2nd gen) entry points for scheduled + real-time alerts.

`scheduled_brief` is triggered by Cloud Scheduler on a cron. Runs the exact
same pipeline as the Streamlit app -- deterministic analytics -> Gemini
executive brief -> save to Firestore -- then emails the brief via Gmail
SMTP. This is what turns CivicPulse from "a dashboard someone has to
remember to open" into a service that delivers a decision to an inbox on
its own schedule.

`send_realtime_alert` is triggered on demand from the app's Recommendations
tab the moment a generated brief contains an immediate-urgency action --
it doesn't recompute anything, just emails the subject/body the app already
built from the live session's brief, using the same `_send_email` helper.

Reuses src/ directly (no duplicated logic): the brief a scheduled run
produces is identical in shape to one generated by clicking the button in the
UI, and shows up in the same Firestore-backed history.

Deploy (see README for the full one-time setup):
  gcloud functions deploy civicpulse-scheduled-brief \
    --gen2 --runtime=python312 --region=us-central1 \
    --source=. --entry-point=scheduled_brief --trigger-http \
    --no-allow-unauthenticated \
    --set-env-vars=GOOGLE_GENAI_USE_VERTEXAI=true,GOOGLE_CLOUD_PROJECT=<project>,GOOGLE_CLOUD_LOCATION=us-central1,ALERT_SENDER=<gmail>,ALERT_RECIPIENT=<recipient> \
    --set-secrets=GMAIL_APP_PASSWORD=civicpulse-gmail-app-password:latest

  gcloud functions deploy civicpulse-realtime-alert \
    --gen2 --runtime=python312 --region=us-central1 \
    --source=. --entry-point=send_realtime_alert --trigger-http \
    --no-allow-unauthenticated \
    --set-env-vars=ALERT_SENDER=<gmail>,ALERT_RECIPIENT=<recipient> \
    --set-secrets=GMAIL_APP_PASSWORD=civicpulse-gmail-app-password:latest
"""

from __future__ import annotations

import os
import smtplib
from email.message import EmailMessage
from pathlib import Path

import functions_framework

from src.analytics import compute_insights
from src.data_loader import _coerce_types, _map_columns, load_sample
from src.department_contacts import recipients_for
from src.gemini_client import GeminiClient
from src.history_store import HistoryStore

APP_DIR = Path(__file__).parent
SAMPLE_CSV = APP_DIR / "sample_data" / "citizen_complaints.csv"


def _load_dataframe():
    """Bundled sample by default; set CIVICPULSE_DATA_GCS_URI (gs://... or
    https://... CSV) to point a scheduled run at a real dataset instead --
    same column auto-mapping the upload path in the UI uses."""
    data_uri = os.environ.get("CIVICPULSE_DATA_GCS_URI")
    if not data_uri:
        return load_sample(str(SAMPLE_CSV)).df

    import pandas as pd

    df = pd.read_csv(data_uri)
    df, _warnings, _matches = _map_columns(df)
    return _coerce_types(df)


def _send_email(subject: str, body: str, recipients: list[str] | None = None) -> None:
    """Send one email. `recipients` overrides ALERT_RECIPIENT -- used for
    department-scoped reports where each department has its own contact
    list; the citywide report keeps using ALERT_RECIPIENT by omitting it."""
    sender = os.environ.get("ALERT_SENDER")
    app_password = os.environ.get("GMAIL_APP_PASSWORD")
    to_list = recipients if recipients is not None else [os.environ.get("ALERT_RECIPIENT")]
    to_list = [r for r in to_list if r]
    if not (sender and app_password and to_list):
        raise RuntimeError("ALERT_SENDER, GMAIL_APP_PASSWORD, and at least one recipient must be set.")
    # Google displays the app password as four 4-char groups separated by
    # spaces for readability; the real credential has no whitespace. Copying
    # it from a rendered web page sometimes carries over non-breaking spaces
    # (U+00A0) instead of plain ones, which smtplib's ASCII-encoding login
    # step chokes on -- strip all whitespace defensively so this works
    # regardless of how it was pasted in.
    app_password = "".join(app_password.split())

    # EmailMessage (not the legacy MIMEText + as_string()) so non-ASCII
    # characters in Gemini's output -- e.g. a non-breaking space or smart
    # punctuation -- get RFC 2047 / quoted-printable encoded automatically
    # instead of raising a UnicodeEncodeError during serialization.
    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = ", ".join(to_list)
    msg.set_content(body)

    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.starttls()
        server.login(sender, app_password)
        server.send_message(msg)


def _brief_to_email_body(data: dict) -> str:
    lines = []
    if data.get("dataset_overview"):
        lines += ["What this data is:", data["dataset_overview"], ""]
    lines += [data.get("summary", ""), "", "Key findings:"]
    lines += [f"- {f}" for f in data.get("key_findings", [])] or ["- (none)"]
    patterns = data.get("peculiar_patterns") or data.get("anomalies")
    if patterns:
        lines += ["", "Peculiar patterns:"] + [f"- {a}" for a in patterns]
    lines += ["", "Recommended actions (respond by urgency -- IMMEDIATE means today/ASAP):"]
    for i, act in enumerate(data.get("recommended_actions", []), 1):
        if isinstance(act, dict):
            urgency = str(act.get("urgency", "")).upper()
            lines.append(
                f"{i}. [{urgency or 'N/A'}] {act.get('action', '')} "
                f"(owner: {act.get('owner', '—')}, timeframe: {act.get('timeframe', '—')})"
            )
        else:
            lines.append(f"{i}. {act}")
    lines += ["", f"Confidence: {str(data.get('confidence', '—')).title()}"]
    lines += ["", "-- Generated automatically by CivicPulse AI (Cloud Scheduler)."]
    return "\n".join(lines)


def _department_slice(df, department: str):
    return df[df["department"].astype(str) == department]


@functions_framework.http
def scheduled_brief(request):
    """HTTP entry point Cloud Scheduler calls. Returns a small JSON status
    body so the Scheduler job's execution log shows what actually happened.

    Sends two kinds of email:
      1. The citywide brief (unchanged from before) to ALERT_RECIPIENT.
      2. One brief per department found in the data, scoped to ONLY that
         department's records, to the recipients configured in
         src/department_contacts.py. A department with no configured
         contact is skipped (reported, not treated as a failure) -- routing
         never guesses an address.
    """
    domain = os.environ.get("ALERT_DOMAIN", "citizen complaints")

    df = _load_dataframe()
    insights = compute_insights(df)
    payload = insights.to_dict()

    gemini = GeminiClient()
    history = HistoryStore()

    # ---------------------------------------------------------- citywide
    result = gemini.executive_brief(payload, domain)
    data = result.data
    saved_id = None
    if result.ok:
        saved_id = history.save_brief(
            domain=domain, source_type="scheduled", insights=payload, brief_data=data
        )

    subject = f"CivicPulse AI — {data.get('title', 'Weekly Brief')}"
    body = _brief_to_email_body(data)
    try:
        _send_email(subject, body)
        email_status = "sent"
    except Exception as exc:  # noqa: BLE001 - report, don't crash the scheduled run
        email_status = f"failed: {exc}"

    # ---------------------------------------------------- department-scoped
    department_status: dict[str, str] = {}
    departments = (
        sorted(df["department"].dropna().astype(str).unique().tolist())
        if "department" in df.columns
        else []
    )
    for dept in departments:
        recipients = recipients_for(dept)
        if not recipients:
            department_status[dept] = "skipped (no contact configured)"
            continue

        dept_df = _department_slice(df, dept)
        if dept_df.empty:
            department_status[dept] = "skipped (no records)"
            continue

        dept_payload = compute_insights(dept_df).to_dict()
        dept_result = gemini.executive_brief(dept_payload, domain)
        dept_data = dept_result.data
        if dept_result.ok:
            history.save_brief(
                domain=f"{domain} — {dept}",
                source_type="scheduled_department",
                insights=dept_payload,
                brief_data=dept_data,
            )

        dept_subject = f"CivicPulse AI — {dept} Weekly Report"
        dept_body = _brief_to_email_body(dept_data)
        try:
            _send_email(dept_subject, dept_body, recipients=recipients)
            department_status[dept] = f"sent to {len(recipients)} recipient(s)"
        except Exception as exc:  # noqa: BLE001 - one department's failure shouldn't skip the rest
            department_status[dept] = f"failed: {exc}"

    return {
        "ok": True,
        "gemini_used_fallback": result.used_fallback,
        "saved_brief_id": saved_id,
        "email_status": email_status,
        "department_reports": department_status,
    }, 200


@functions_framework.http
def send_realtime_alert(request):
    """HTTP entry point the app's Recommendations tab calls the moment a
    freshly generated brief (dataset-wide or OCR-scanned) contains an
    immediate-urgency action. Unlike scheduled_brief, this does no analytics
    or Gemini calls of its own -- the app already has the live brief in the
    user's session and built the subject/body from it, so this function's
    only job is the one thing that needs a server-side secret: sending the
    email via Gmail SMTP.

    Expects a JSON body: {"subject": str, "body": str}. Returns a small JSON
    status so a demo click gets an immediate, honest success/failure signal.
    """
    body_json = request.get_json(silent=True) or {}
    subject = str(body_json.get("subject") or "CivicPulse AI Real-Time Alert")
    body = str(body_json.get("body") or "")
    if not body.strip():
        return {"ok": False, "email_status": "failed: empty alert body"}, 400

    try:
        _send_email(subject, body)
        return {"ok": True, "email_status": "sent"}, 200
    except Exception as exc:  # noqa: BLE001 - report, don't 500 a demo click
        return {"ok": False, "email_status": f"failed: {exc}"}, 200
