"""Cloud Function (2nd gen) entry point for the scheduled Executive Brief.

Triggered by Cloud Scheduler on a cron. Runs the exact same pipeline as the
Streamlit app -- deterministic analytics -> Gemini executive brief -> save to
Firestore -- then emails the brief via Gmail SMTP. This is what turns
CivicPulse from "a dashboard someone has to remember to open" into a service
that delivers a decision to an inbox on its own schedule.

Reuses src/ directly (no duplicated logic): the brief a scheduled run
produces is identical in shape to one generated by clicking the button in the
UI, and shows up in the same Firestore-backed history.

Deploy (see README for the full one-time setup):
  gcloud functions deploy civicpulse-scheduled-brief \
    --gen2 --runtime=python312 --region=us-central1 \
    --source=. --entry-point=scheduled_brief --trigger-http \
    --no-allow-unauthenticated \
    --set-env-vars=GOOGLE_GENAI_USE_VERTEXAI=true,GOOGLE_CLOUD_PROJECT=<project>,GOOGLE_CLOUD_LOCATION=us-central1,ALERT_SENDER=<gmail>,ALERT_RECIPIENT=<recipient> \
    --set-secrets=GMAIL_APP_PASSWORD=civicpulse-gmail-app-password:latest
"""

from __future__ import annotations

import os
import smtplib
from email.message import EmailMessage
from pathlib import Path

import functions_framework

from src.analytics import compute_insights
from src.data_loader import _coerce_types, _map_columns, load_sample
from src.gemini_client import GeminiClient
from src.history_store import HistoryStore

APP_DIR = Path(__file__).parent
SAMPLE_CSV = APP_DIR / "sample_data" / "citizen_complaints.csv"


def _load_dataframe():
    """Bundled sample by default; set CIVICPULSE_DATA_GCS_URI (gs://... or
    https://... CSV) to point a scheduled run at a real dataset instead --
    same column auto-mapping the upload path in the UI uses."""
    data_uri = os.environ.get("CIVICPULSE_DATA_GCS_URI")
    if not data_uri:
        return load_sample(str(SAMPLE_CSV)).df

    import pandas as pd

    df = pd.read_csv(data_uri)
    df, _warnings, _matches = _map_columns(df)
    return _coerce_types(df)


def _send_email(subject: str, body: str) -> None:
    sender = os.environ.get("ALERT_SENDER")
    recipient = os.environ.get("ALERT_RECIPIENT")
    app_password = os.environ.get("GMAIL_APP_PASSWORD")
    if not (sender and recipient and app_password):
        raise RuntimeError("ALERT_SENDER, ALERT_RECIPIENT, and GMAIL_APP_PASSWORD must all be set.")
    # Google displays the app password as four 4-char groups separated by
    # spaces for readability; the real credential has no whitespace. Copying
    # it from a rendered web page sometimes carries over non-breaking spaces
    # (U+00A0) instead of plain ones, which smtplib's ASCII-encoding login
    # step chokes on -- strip all whitespace defensively so this works
    # regardless of how it was pasted in.
    app_password = "".join(app_password.split())

    # EmailMessage (not the legacy MIMEText + as_string()) so non-ASCII
    # characters in Gemini's output -- e.g. a non-breaking space or smart
    # punctuation -- get RFC 2047 / quoted-printable encoded automatically
    # instead of raising a UnicodeEncodeError during serialization.
    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = recipient
    msg.set_content(body)

    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.starttls()
        server.login(sender, app_password)
        server.send_message(msg)


def _brief_to_email_body(data: dict) -> str:
    lines = [data.get("summary", ""), "", "Key findings:"]
    lines += [f"- {f}" for f in data.get("key_findings", [])] or ["- (none)"]
    if data.get("anomalies"):
        lines += ["", "Anomalies:"] + [f"- {a}" for a in data["anomalies"]]
    lines += ["", "Recommended actions:"]
    for i, act in enumerate(data.get("recommended_actions", []), 1):
        if isinstance(act, dict):
            lines.append(
                f"{i}. {act.get('action', '')} "
                f"(owner: {act.get('owner', '—')}, timeframe: {act.get('timeframe', '—')})"
            )
        else:
            lines.append(f"{i}. {act}")
    lines += ["", f"Confidence: {str(data.get('confidence', '—')).title()}"]
    lines += ["", "-- Generated automatically by CivicPulse AI (Cloud Scheduler)."]
    return "\n".join(lines)


@functions_framework.http
def scheduled_brief(request):
    """HTTP entry point Cloud Scheduler calls. Returns a small JSON status
    body so the Scheduler job's execution log shows what actually happened."""
    domain = os.environ.get("ALERT_DOMAIN", "citizen complaints")

    df = _load_dataframe()
    insights = compute_insights(df)
    payload = insights.to_dict()

    gemini = GeminiClient()
    result = gemini.executive_brief(payload, domain)
    data = result.data

    history = HistoryStore()
    saved_id = None
    if result.ok:
        saved_id = history.save_brief(
            domain=domain, source_type="scheduled", insights=payload, brief_data=data
        )

    subject = f"CivicPulse AI — {data.get('title', 'Weekly Brief')}"
    body = _brief_to_email_body(data)
    try:
        _send_email(subject, body)
        email_status = "sent"
    except Exception as exc:  # noqa: BLE001 - report, don't crash the scheduled run
        email_status = f"failed: {exc}"

    return {
        "ok": True,
        "gemini_used_fallback": result.used_fallback,
        "saved_brief_id": saved_id,
        "email_status": email_status,
    }, 200
